project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/logo.png
    left:
      - text: "Projects"
        href: project.html
      - text: "CV"
        href: about.html

    
    tools:
        - icon: github
          href: https://github.com/KirstinLyon
        - icon: linkedin
          href: https://www.linkedin.com/in/kirstin-lyon-0320012a/
        - icon: medium
          href: https://medium.com/@kirstin.lyon
        - icon: envelope
          href: mailto:kirstin@mltwelve.com

format:
  html:
    theme: flatly
    css: styles.css
    toc: false


