project:
  type: website
  output-dir: docs

website:
  title: "MLTwelve"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test.qmd

format:
  html:
    theme:
      - lux
      - brand
    backgroundcolor: "#F2E9E4"
    css: styles.css
    toc: true

editor: visual

