project:
  type: website
  output-dir: docs

website:
  title: "MLTwelve"

format:
  html:
    theme:
      - lux
      - brand
    backgroundcolor: "#F2E9E4"
    css: styles.css
    toc: false

editor: visual

